#pragma once
#ifndef _COMMON_H_
#define _COMMON_H_

typedef enum
{
	PLAYER_ATTACK_TYPE_NONE = 0,
	WSWORD_ATTACK_01,
	WSWORD_ATTACK_02,
	WSWORD_ATTACK_03,
	WSWORD_ATTACK_04,
	CLAYMORE_ATTACK_01,
	CLAYMORE_ATTACK_02,
	CLAYMORE_ATTACK_03
}ATTACK_TYPE_PLAYER;

typedef enum
{
	ENEMY_ATTACK_TYPE_NONE = 0,
	DOG_BITE_ATTACK,
	DOG_JUMP_ATTACK
}ATTACK_TYPE_ENEMY;

#endif