#ifndef CNAVMESH_MANAGER_H_
#define CNAVMESH_MANAGER_H_

//インクルードヘッダ
#include "CNavMesh.h"
#include <array>

#define NAVMESH_MAX_NUM (600)

//クラス定義
class CNavMeshManager
{
public:
	CNavMeshManager();
	~CNavMeshManager();

	void UpdateAll(void);
	void DrawAllNavMeshAndConnect(void);
	void UninitAll(void);

	CNavMesh* GetPointer(int NavMeshID);
	void SetAllNavMeshNoCheck(void);
	void NoUseAllNavMesh(void);
	int CalcPlayerInMeshNumber(const D3DXVECTOR3& PlayerPosition);
	void AutoGeneratedNavMesh(const D3DXVECTOR2& MasuNum,const D3DXVECTOR3& size, const D3DXVECTOR2& Dist);		//配置したオブジェクトのAABBと当り判定をし、自動ナビメッシュを生成する

	CNavMesh* CreateNewNavMesh(const D3DXVECTOR3& pos, const D3DXVECTOR3& size, bool CanWalkFlag);

private:
	std::array<CNavMesh, NAVMESH_MAX_NUM>	m_NavMeshArray;						//ナビメッシュの配列
	int										m_PlayerPositionInMeshNumber;		//プレーヤーの位置はどのナビメッシュにいるか
};

#endif